// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-DwNbzbhh4YD9nnHrmPV4oISDKQOHzPQ',
    appId: '1:336677721325:web:63934e985a6ec8b2b8e8e4',
    messagingSenderId: '336677721325',
    projectId: 'canvas-cffc8',
    authDomain: 'canvas-cffc8.firebaseapp.com',
    storageBucket: 'canvas-cffc8.firebasestorage.app',
    measurementId: 'G-51NP2NFR9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmi8k89BVkO9HKv5phNlfCS3p916-JNhg',
    appId: '1:336677721325:android:46f45f1183f8edb9b8e8e4',
    messagingSenderId: '336677721325',
    projectId: 'canvas-cffc8',
    storageBucket: 'canvas-cffc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhbzLTeQlkzSWiWyQgYCJOhOM_VSNT6V0',
    appId: '1:336677721325:ios:e60b3c51a72b40a5b8e8e4',
    messagingSenderId: '336677721325',
    projectId: 'canvas-cffc8',
    storageBucket: 'canvas-cffc8.firebasestorage.app',
    iosBundleId: 'com.example.infinitiveCanvas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhbzLTeQlkzSWiWyQgYCJOhOM_VSNT6V0',
    appId: '1:336677721325:ios:e60b3c51a72b40a5b8e8e4',
    messagingSenderId: '336677721325',
    projectId: 'canvas-cffc8',
    storageBucket: 'canvas-cffc8.firebasestorage.app',
    iosBundleId: 'com.example.infinitiveCanvas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-DwNbzbhh4YD9nnHrmPV4oISDKQOHzPQ',
    appId: '1:336677721325:web:37a6ef39b949494fb8e8e4',
    messagingSenderId: '336677721325',
    projectId: 'canvas-cffc8',
    authDomain: 'canvas-cffc8.firebaseapp.com',
    storageBucket: 'canvas-cffc8.firebasestorage.app',
    measurementId: 'G-8KK139SVZR',
  );
}
